Repository S-FAM/PyeonHaeng, pull requests merged in 2022-11, with the labels that each got.

#29 [BUG] Coordinator 주입 누락
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkCoordinator.swift
  PPAK_CVS/Sources/Scenes/Home/HomeCoordinator.swift
  PPAK_CVS/Sources/Scenes/Onboarding/OnboardingCoordinator.swift
  PPAK_CVS/Sources/Scenes/Product/ProductCoordinator.swift
Labels: 🐞Bug

#23 Feat/common/uiextension
  PPAK_CVS/Configuration/Extensions/UIColor+.swift
Labels: ✨Enhancement

#28 Refactor/bookmark scenes with ReactorKit & 화면전환 구현
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS.xcodeproj/project.xcworkspace/xcuserdata/eungcheol.xcuserdatad/UserInterfaceState.xcuserstate
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkCollectionHeaderView.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkCoordinator.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkViewModel.swift
  PPAK_CVS/Sources/Scenes/Home/HomeCoordinator.swift
  PPAK_CVS/Sources/Scenes/Home/HomeVC.swift
  PPAK_CVS/Sources/Scenes/Home/HomeViewModel.swift
Labels: ✨Enhancement, 🏠Home, 🔖Bookmark

#30 코드 정리
  PPAK_CVS/Configuration/Constants/Enum/CvsType.swift
  PPAK_CVS/Configuration/Constants/Enum/EventType.swift
  PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
  PPAK_CVS/Sources/Scenes/Common/FilterDropdownView.swift
  PPAK_CVS/Sources/Scenes/Common/TitleLogoView.swift
  PPAK_CVS/Sources/Scenes/Onboarding/FTUXStorage.swift
Labels: ✨Enhancement

#31 UIColor Initializer 개정
  PPAK_CVS/Configuration/Extensions/UIColor+.swift
Labels: ✨Enhancement

#37 OnboardingVC 이전 페이지 버그 수정
  PPAK_CVS/Sources/Scenes/Onboarding/OnboardingViewModel.swift
Labels: 🐞Bug, 👟Onboarding

#36 OnboardingVC 하단 배경 색상 변경
  PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift
Labels: 👟Onboarding

#35 OnboardingVC 효과 추가
  PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift
Labels: 👟Onboarding

#38 Firebase DB 클래스 구현
  .gitignore
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Constants/Enum/CvsType.swift
  PPAK_CVS/Configuration/Constants/Enum/EventType.swift
  PPAK_CVS/Configuration/Constants/Enum/SortType.swift
  PPAK_CVS/Configuration/Extensions/Date+.swift
  PPAK_CVS/Sources/AppDelegate.swift
  PPAK_CVS/Sources/Managers/CVSDatabase.swift
  PPAK_CVS/Sources/Models/ProductModel.swift
  PPAK_CVS/Sources/Models/RequestTypeModel.swift
  PPAK_CVS/Sources/Scenes/Common/TitleLogoView.swift
Labels: ✨Enhancement

#43 CVSDatabase 수정
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Sources/Managers/CVSDatabase.swift
  PPAK_CVS/Sources/Models/EventInfoResponseModel.swift
Labels: 🐞Bug

#41 네트워크 끊겼을 때 처리했습니다
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Constants/Enum/Strings.swift
  PPAK_CVS/Sources/AppDelegate.swift
  PPAK_CVS/Sources/Managers/NetworkCheck.swift
  PPAK_CVS/Sources/Scenes/Network/NetworkVC.swift
Labels: ✨Enhancement

#44 [Home] Cell Pagination 구현
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS.xcodeproj/project.xcworkspace/xcuserdata/eungcheol.xcuserdatad/UserInterfaceState.xcuserstate
  PPAK_CVS.xcodeproj/xcuserdata/eungcheol.xcuserdatad/xcschemes/xcschememanagement.plist
  PPAK_CVS/Sources/Managers/CVSDatabase.swift
  PPAK_CVS/Sources/Scenes/Common/LoadingCell.swift
  PPAK_CVS/Sources/Scenes/Home/HomeVC.swift
  PPAK_CVS/Sources/Scenes/Home/HomeViewModel.swift
Labels: ✨Enhancement, 🏠Home
