Repository S-FAM/PyeonHaeng, pull requests merged in 2022-12, with the labels that each got.

#46 Feat/setting vc UI
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_alert.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_alert.imageset/icon_alert 1.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_alert.imageset/icon_alert 2.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_alert.imageset/icon_alert.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_left.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_left.imageset/icon_left 1.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_left.imageset/icon_left 2.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_left.imageset/icon_left.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_mail.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_mail.imageset/icon_mail 1.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_mail.imageset/icon_mail 2.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_mail.imageset/icon_mail.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_noti.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_noti.imageset/icon_noti 1.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_noti.imageset/icon_noti 2.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_noti.imageset/icon_noti.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_review.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_review.imageset/icon_review 1.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_review.imageset/icon_review 2.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_review.imageset/icon_review.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_version.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_version.imageset/icon_version 1.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_version.imageset/icon_version 2.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/icon_version.imageset/icon_version.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/info_cheer.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/info_cheer.imageset/info_cheer 1.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/info_cheer.imageset/info_cheer 2.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/settingVC_image/info_cheer.imageset/info_cheer.png
  PPAK_CVS/Configuration/Extensions/NSAttributedString+.swift
  PPAK_CVS/SettingTableViewCell.swift
  PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
Labels: 🍎ConfigureUI, ⚙️Setting

#48 API Refactoring
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Sources/Models/RequestProductNameModel.swift
  PPAK_CVS/Sources/Models/RequestTypeModel.swift
  PPAK_CVS/Sources/Network/ProductTarget.swift
  PPAK_CVS/Sources/Network/PyeonHaengAPI.swift
Labels: ✨Enhancement

#50 [Fix] Home UI
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Assets/Assets.xcassets/Magnifying_Glass.imageset/akar-icons_search.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/Magnifying_Glass.imageset/akar-icons_search@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/Magnifying_Glass.imageset/akar-icons_search@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/filter.imageset/fluent_filter-12-filled.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/filter.imageset/fluent_filter-12-filled@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/filter.imageset/fluent_filter-12-filled@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_convenienceStore.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_convenienceStore.imageset/Group 542.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_convenienceStore.imageset/Group 542@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_convenienceStore.imageset/Group 542@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_convenienceStore_clear.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_convenienceStore_clear.imageset/Group 539.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_convenienceStore_clear.imageset/Group 539@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_convenienceStore_clear.imageset/Group 539@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_gear.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_gear.imageset/Group 8.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_gear.imageset/Group 8@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_gear.imageset/Group 8@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_heart_white.imageset/8673445_ic_fluent_heart_circle_filled_icon-2 1.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_heart_white.imageset/8673445_ic_fluent_heart_circle_filled_icon-2 1@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_heart_white.imageset/8673445_ic_fluent_heart_circle_filled_icon-2 1@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_heart_white.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_info.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_info.imageset/eva_info-outline.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_info.imageset/eva_info-outline@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_info.imageset/eva_info-outline@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_magnifyingGlass.imageset/8673694_ic_fluent_search_filled_icon 3.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_magnifyingGlass.imageset/8673694_ic_fluent_search_filled_icon 3@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_magnifyingGlass.imageset/8673694_ic_fluent_search_filled_icon 3@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_magnifyingGlass.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_sort.imageset/8672817_ic_fluent_arrow_sort_filled_icon 2.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_sort.imageset/8672817_ic_fluent_arrow_sort_filled_icon 2@2x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_sort.imageset/8672817_ic_fluent_arrow_sort_filled_icon 2@3x.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_sort.imageset/Contents.json
  PPAK_CVS/Configuration/Constants/Enum/CvsType.swift
  PPAK_CVS/Info.plist
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
  PPAK_CVS/Sources/Scenes/Common/CVSDropdownView.swift
  PPAK_CVS/Sources/Scenes/Common/SearchBar.swift
  PPAK_CVS/Sources/Scenes/Common/SortDropdownView.swift
  PPAK_CVS/Sources/Scenes/Home/HomeCollectionHeaderView.swift
  PPAK_CVS/Sources/Scenes/Home/HomeVC.swift
Labels: 🏠Home

#49 [CHORE] Coordinator settings using `some` and `any`
  PPAK_CVS/Configuration/Base/BaseCoordinator.swift
  PPAK_CVS/Configuration/Base/Coordinator.swift
Labels: ✨Enhancement

#53 [Feat] 찜목록 저장소 구현
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Sources/Models/ProductModel.swift
  PPAK_CVS/Sources/Storage/Storage.swift
Labels: ✨Enhancement

#55 [REFACTOR] Xcode project settings
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Sources/AppDelegate.swift
  PPAK_CVS/Sources/Network/CVSDatabase.swift
  PPAK_CVS/Sources/Scenes/Home/HomeViewModel.swift
Labels: ✨Enhancement
