Repository S-FAM/PyeonHaeng, pull requests merged in 2023-02, with the labels that each got.

#82 SelectStoreVC(자주 가는 편의점) 구현
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_check.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_check.imageset/HGEuE.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_check.imageset/ls60J.png
  PPAK_CVS/Configuration/Assets/Assets.xcassets/ic_check.imageset/mXwGj.png
  PPAK_CVS/Configuration/Assets/Fonts/EF_jejudoldam.otf
  PPAK_CVS/Configuration/Constants/Enum/Strings.swift
  PPAK_CVS/Configuration/Extensions/UIButton+.swift
  PPAK_CVS/Configuration/Extensions/UIFont+.swift
  PPAK_CVS/Info.plist
  PPAK_CVS/Sources/AppCoordinator.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkCoordinator.swift
  PPAK_CVS/Sources/Scenes/Home/HomeCoordinator.swift
  PPAK_CVS/Sources/Scenes/Home/HomeViewReactor.swift
  PPAK_CVS/Sources/Scenes/Onboarding/OnboardingCoordinator.swift
  PPAK_CVS/Sources/Scenes/Onboarding/OnboardingViewReactor.swift
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreCoordinator.swift
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreStackView.swift
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreVC.swift
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreView.swift
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreViewReactor.swift
  PPAK_CVS/Sources/Storage/CVSStorage.swift
Labels: 👟Onboarding, ⚙️Setting

#83 ProductVC 버튼 액션 구현 및 버그 수정
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Sources/Scenes/Common/TitleLogoView.swift
  PPAK_CVS/Sources/Scenes/Product/ProductCollectionHeaderView.swift
  PPAK_CVS/Sources/Scenes/Product/ProductCoordinator.swift
  PPAK_CVS/Sources/Scenes/Product/ProductHeaderViewReactor.swift
  PPAK_CVS/Sources/Scenes/Product/ProductVC.swift
  PPAK_CVS/Sources/Scenes/Product/ProductViewReactor.swift
Labels: 📱Product

#84 [CHORE]SettingVC - TableView셀 클릭시, 공지사항동작 세팅
  PPAK_CVS/Sources/Scenes/Setting/SettingCoordinator.swift
  PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
  PPAK_CVS/Sources/Scenes/Setting/SettingViewReactor.swift
Labels: ⚙️Setting

#85 자주 가는 편의점 화면 - 체크 해제 기능 구현
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreVC.swift
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreView.swift
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreViewReactor.swift
Labels: ✨Enhancement

#86 Storage 리팩토링
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Manager/UserDefaultsWrapper.swift
  PPAK_CVS/Sources/AppCoordinator.swift
  PPAK_CVS/Sources/Storage/CVSStorage.swift
  PPAK_CVS/Sources/Storage/FTUXStorage.swift
  PPAK_CVS/Sources/Storage/ProductStorage.swift
Labels: ♻️Refactoring

#87 [API] 이전 행사 내역 추가
  PPAK_CVS/Sources/Models/ProductModel.swift
  PPAK_CVS/Sources/Network/ProductTarget.swift
  PPAK_CVS/Sources/Network/PyeonHaengAPI.swift
  PPAK_CVS/Sources/Scenes/Home/HomeViewReactor.swift
  PPAK_CVS/Sources/Scenes/Product/ProductCoordinator.swift
  PPAK_CVS/Sources/Scenes/Product/ProductVC.swift
  PPAK_CVS/Sources/Scenes/Product/ProductViewReactor.swift
Labels: ✨Enhancement

#88 [ADD] Xcode APNs 환경 세팅
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Info.plist
  PPAK_CVS/PPAK_CVS.entitlements
Labels: ✨Enhancement

#89 설정 - 공지사항 구현
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Constants/Enum/Strings.swift
  PPAK_CVS/NoticeInfo.plist
  PPAK_CVS/Sources/AppDelegate.swift
  PPAK_CVS/Sources/Scenes/Notice/NoticeCoordinator.swift
  PPAK_CVS/Sources/Scenes/Notice/NoticeVC.swift
  PPAK_CVS/Sources/Scenes/Notice/NoticeViewReactor.swift
  PPAK_CVS/Sources/Scenes/Setting/SettingCoordinator.swift
Labels: ⚙️Setting

#90 [Fix] 찜목록 Lottie 버그 수정
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkViewReactor.swift
  PPAK_CVS/Sources/Scenes/Home/HomeViewReactor.swift
Labels: 🐞Bug

#91 SettingViewcontroller - TableSelectEvent : set ReactorKit
  PPAK_CVS/Configuration/Assets/Assets.xcassets/Settings/icon_selectStore.imageset/Contents.json
  PPAK_CVS/Configuration/Assets/Assets.xcassets/Settings/icon_selectStore.imageset/icon_selectStore.png
  PPAK_CVS/Configuration/Constants/Enum/SettingCellType.swift
  PPAK_CVS/Sources/Scenes/Setting/SettingCoordinator.swift
  PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
  PPAK_CVS/Sources/Scenes/Setting/SettingViewReactor.swift
Labels: ⚙️Setting

#92 [Product] 이전 행사 내역 구현
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Sources/Models/ProductModel.swift
  PPAK_CVS/Sources/Models/RequestHistoryModel.swift
  PPAK_CVS/Sources/Network/ProductTarget.swift
  PPAK_CVS/Sources/Network/PyeonHaengAPI.swift
  PPAK_CVS/Sources/Scenes/Product/ProductCollectionHeaderView.swift
  PPAK_CVS/Sources/Scenes/Product/ProductVC.swift
  PPAK_CVS/Sources/Scenes/Product/ProductViewReactor.swift
Labels: 📱Product

#95 [Refactoring] 전체 코드
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Base/BaseViewController.swift
  PPAK_CVS/Configuration/Constants/Enum/CvsType.swift
  PPAK_CVS/Configuration/Extensions/Preview.swift
  PPAK_CVS/Sources/Models/OnboardingDataModel.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
  PPAK_CVS/Sources/Scenes/Home/HomeVC.swift
  PPAK_CVS/Sources/Scenes/Notice/NoticeVC.swift
  PPAK_CVS/Sources/Scenes/Onboarding/OnboardingVC.swift
  PPAK_CVS/Sources/Scenes/Setting/SettingVC.swift
Labels: ♻️Refactoring

#96 SelectStoreVC 기기대응 레이아웃 구현
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Configuration/Manager/DeviceManager.swift
  PPAK_CVS/Sources/Scenes/SelectStore/SelectStoreVC.swift
Labels: 🐞Bug

#97 FCM(Firebase Cloud Messaging) 구현
  PPAK_CVS.xcodeproj/project.pbxproj
  PPAK_CVS/Sources/AppDelegate.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkCollectionHeaderView.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
Labels: ✨Enhancement

#98 [ADD] 공유 이미지 패딩 처리
  PPAK_CVS/Sources/Scenes/Product/ProductCollectionHeaderView.swift
Labels: ✨Enhancement

#99 [FIX] 등록한 찜목록이 해제되는 버그 수정
  PPAK_CVS/Sources/Scenes/Product/ProductCoordinator.swift
  PPAK_CVS/Sources/Scenes/Product/ProductViewReactor.swift
Labels: 🐞Bug

#100 [BUG] 제품 상세 페이지 retain cycle
  PPAK_CVS/Sources/Scenes/Product/ProductVC.swift
Labels: 🐞Bug

#101 [BUG] NavigationController PopGesture 버그 수정
  PPAK_CVS/Configuration/Base/BaseViewController.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkVC.swift
  PPAK_CVS/Sources/Scenes/Bookmark/BookmarkViewReactor.swift
  PPAK_CVS/Sources/Scenes/Home/HomeViewReactor.swift
Labels: 🐞Bug

#102 [FEAT] Setting Topics to receive apns
  PPAK_CVS/Sources/AppDelegate.swift
Labels: ✨Enhancement

#103 [CHORE] 설정 창에서 문의 보내기 이메일 수정
  PPAK_CVS/Sources/Scenes/Setting/SettingConfig.swift
Labels: 🍎ConfigureUI, ✨Enhancement
